import { createMarkdownToRichTextContent } from '../content';
import { getBibliography } from '../bibliography';

export const content = createMarkdownToRichTextContent({
  locale: 'de', slug: 'markdown-zu-rich-text', title: 'Markdown in Rich Text umwandeln: Formatiertes HTML kopieren', description: 'Wandeln Sie Markdown in eine Rich-Text-Vorschau mit kopierfertigem HTML um. Die Verarbeitung erfolgt direkt im Browser.', bibliography: getBibliography('de'),
  faq: [
    { question: 'Was erzeugt dieser Markdown-zu-Rich-Text-Konverter?', answer: 'Er wandelt unterstütztes Markdown in semantisch formatierten Rich Text um, den Sie prüfen und in einen Editor, eine E-Mail oder ein Dokument einfügen können.' },
    { question: 'Welche Markdown-Funktionen werden unterstützt?', answer: 'Unterstützt werden Überschriften, Absätze, Hervorhebungen, Links, Bilder, Zitate, Listen, Inline-Code, Codeblöcke und horizontale Linien.' },
    { question: 'Warum Rich Text statt Markdown verwenden?', answer: 'Viele Editoren übernehmen Formatierungen beim Einfügen, interpretieren Markdown-Syntax jedoch nicht. Dieses Tool verbindet beide Arbeitsweisen.' },
    { question: 'Sieht die Formatierung überall gleich aus?', answer: 'Rich-Text-Editoren verwenden eigene Stile und unterstützen unterschiedliche HTML-Funktionen. Kleine visuelle Unterschiede zwischen Apps sind möglich.' },
  ],
  howTo: [{ name: 'Markdown einfügen', text: 'Fügen Sie Ihr Markdown-Dokument in das Quellfeld ein.' }, { name: 'Vorschau prüfen', text: 'Prüfen Sie die gerenderte Rich-Text-Seite und ihre Struktur.' }, { name: 'Rich Text kopieren', text: 'Kopieren Sie das Ergebnis und fügen Sie es in Ihr Dokument, Ihre E-Mail oder Ihren Editor ein.' }],
  seoTitle: 'Markdown in kopierfertigen Rich Text umwandeln', seoIntro: 'Markdown eignet sich hervorragend zum Schreiben und für Versionsverwaltung, doch viele E-Mail-Editoren, Dokumente und CMS-Felder erwarten Rich Text. Dieses Tool erstellt eine semantische HTML-Version Ihres Markdowns.', seoWorkflowTitle: 'Ein klarer Konvertierungsablauf', seoWorkflow: 'Fügen Sie vorhandenes Markdown ein, prüfen Sie die Vorschau und kopieren Sie das formatierte Ergebnis. Überschriften, Absätze, Listen, Links, Zitate, Code und Hervorhebungen werden lokal verarbeitet.', seoFeatures: ['<strong>Formatierte Ausgabe:</strong> HTML mit einer Klartext-Alternative kopieren.', '<strong>Klare Grenzen:</strong> der unterstützte Markdown-Umfang bleibt sichtbar.', '<strong>Lokale Verarbeitung:</strong> Ihr Entwurf bleibt im Browser.', '<strong>Praktische Wiederaufnahme:</strong> der letzte Entwurf wird wiederhergestellt.'],
  ui: { labelKicker: 'Markdown-Arbeitsfläche', labelInput: 'Markdown-Quelle', labelPreview: 'Rich-Text-Vorschau', placeholderInput: 'Markdown hier einfügen ...', btnExample: 'Beispiel laden', btnClear: 'Leeren', btnCopy: 'Rich Text kopieren', toastCopied: 'Rich Text kopiert!', toastCopyError: 'Kopieren wurde blockiert. Markieren Sie die Vorschau und kopieren Sie sie manuell.', toastRestored: 'Letzten Entwurf wiederhergestellt.', emptyPreview: 'Ihr formatiertes Dokument erscheint hier.', labelHint: 'Unterstützt gängige Markdown-Strukturen. Unsicheres HTML wird maskiert und alles wird im Browser verarbeitet.', labelBlocks: 'Blöcke', labelWords: 'Wörter', labelWarnings: 'Warnungen', warningMessage: 'Ein Teil des Inhalts wurde maskiert oder konnte nicht als sicherer Link behandelt werden.', exampleMarkdown: '# Versionshinweise\n\nEin **fokussiertes** Update mit einem [Projektlink](https://example.com).\n\n- Schnelle lokale Umwandlung\n- Formatierte Zwischenablage\n\n> Fügen Sie das Ergebnis in Ihren Editor ein.\n\n```js\nconst bereit = true;\n```' },
});
