import { createMarkdownToRichTextContent } from '../content';
import { getBibliography } from '../bibliography';

export const content = createMarkdownToRichTextContent({
  locale: 'es', slug: 'markdown-a-texto-enriquecido', title: 'Convertidor de Markdown a texto enriquecido: copia HTML con formato', description: 'Convierte Markdown en texto enriquecido con vista previa y HTML listo para pegar. Todo se procesa en tu navegador.', bibliography: getBibliography('es'),
  faq: [
    { question: '¿Qué genera este convertidor de Markdown a texto enriquecido?', answer: 'Convierte el Markdown compatible en texto enriquecido semántico para revisarlo y pegarlo en un editor, correo, documento o CMS.' },
    { question: '¿Qué funciones de Markdown admite?', answer: 'Admite títulos, párrafos, énfasis, negrita, enlaces, imágenes, citas, listas, código en línea, bloques de código y líneas horizontales.' },
    { question: '¿Por qué usar texto enriquecido en lugar de Markdown?', answer: 'Muchos editores aceptan formato al pegar, pero no interpretan la sintaxis Markdown. Esta herramienta conecta ambos flujos de trabajo.' },
    { question: '¿El formato pegado será idéntico en todas las aplicaciones?', answer: 'Cada editor de texto enriquecido aplica sus propios estilos y admite funciones HTML distintas. Es normal encontrar pequeñas diferencias visuales.' },
  ],
  howTo: [{ name: 'Pega el Markdown', text: 'Pega el documento Markdown en el panel de origen.' }, { name: 'Revisa la vista previa', text: 'Comprueba la página enriquecida y su estructura.' }, { name: 'Copia el texto enriquecido', text: 'Copia el resultado con formato y pégalo en tu documento, correo, CMS o editor.' }],
  seoTitle: 'Convierte Markdown en texto enriquecido listo para pegar', seoIntro: 'Markdown es excelente para escribir y versionar contenido, pero muchos editores de correo, documentos y CMS esperan texto enriquecido. Esta herramienta crea una versión HTML semántica de tu Markdown para copiar su formato.', seoWorkflowTitle: 'Un flujo de conversión directo', seoWorkflow: 'Pega el Markdown que ya tienes, revisa la vista previa y copia el resultado formateado. La herramienta gestiona títulos, párrafos, listas, enlaces, citas, código y énfasis sin cuentas ni subidas.', seoFeatures: ['<strong>Salida enriquecida:</strong> copia HTML con una alternativa de texto plano.', '<strong>Alcance claro:</strong> se documenta la sintaxis Markdown compatible.', '<strong>Flujo local:</strong> tu borrador permanece en el navegador.', '<strong>Recuperación útil:</strong> se restaura tu última iteración.'],
  ui: { labelKicker: 'Mesa de Markdown', labelInput: 'Origen Markdown', labelPreview: 'Vista previa enriquecida', placeholderInput: 'Pega aquí tu Markdown...', btnExample: 'Cargar ejemplo', btnClear: 'Limpiar', btnCopy: 'Copiar texto enriquecido', toastCopied: '¡Texto enriquecido copiado!', toastCopyError: 'La copia fue bloqueada. Selecciona la vista previa y cópiala manualmente.', toastRestored: 'Se ha restaurado tu último borrador.', emptyPreview: 'Tu documento formateado aparecerá aquí.', labelHint: 'Admite estructuras Markdown habituales. El HTML inseguro se escapa y todo se procesa en tu navegador.', labelBlocks: 'bloques', labelWords: 'palabras', labelWarnings: 'avisos', warningMessage: 'Parte del contenido se ha escapado o no se ha podido tratar como un enlace seguro.', exampleMarkdown: '# Notas de la versión\n\nUna actualización **centrada** con un [enlace al proyecto](https://example.com).\n\n- Conversión local rápida\n- Salida enriquecida\n\n> Pega el resultado en tu editor.\n\n```js\nconst listo = true;\n```' },
});
