import { createMarkdownToRichTextContent } from '../content';
import { getBibliography } from '../bibliography';

export const content = createMarkdownToRichTextContent({
  locale: 'fr', slug: 'markdown-vers-texte-riche', title: 'Convertisseur Markdown en texte riche: copier le HTML mis en forme', description: 'Convertissez du Markdown en texte riche avec aperçu en direct et HTML prêt à coller. Tout se passe dans votre navigateur.', bibliography: getBibliography('fr'),
  faq: [
    { question: 'Que produit ce convertisseur Markdown en texte riche ?', answer: 'Il transforme le Markdown pris en charge en texte riche sémantique, à vérifier puis à coller dans un éditeur, un e-mail, un document ou un CMS.' },
    { question: 'Quelles fonctions Markdown sont prises en charge ?', answer: 'Les titres, paragraphes, emphases, liens, images, citations, listes, code en ligne, blocs de code et lignes horizontales sont pris en charge.' },
    { question: 'Pourquoi utiliser du texte riche plutôt que du Markdown ?', answer: 'De nombreux éditeurs conservent la mise en forme au collage, mais ne lisent pas la syntaxe Markdown. Cet outil fait le lien entre les deux formats.' },
    { question: 'La mise en forme sera-t-elle identique partout ?', answer: 'Les éditeurs de texte riche appliquent leurs propres styles et ne prennent pas tous en charge les mêmes éléments HTML. De petites différences sont normales.' },
  ],
  howTo: [{ name: 'Collez le Markdown', text: 'Collez votre document Markdown dans le panneau source.' }, { name: 'Vérifiez l aperçu', text: 'Relisez la page en texte riche et sa structure.' }, { name: 'Copiez le texte riche', text: 'Copiez le résultat mis en forme et collez-le dans votre document, e-mail, CMS ou éditeur.' }],
  seoTitle: 'Transformer du Markdown en texte riche prêt à coller', seoIntro: 'Le Markdown est idéal pour écrire et gérer des versions, mais les messageries, éditeurs de documents et CMS attendent souvent du texte riche. Cet outil crée une version HTML sémantique de votre Markdown.', seoWorkflowTitle: 'Un flux de conversion simple', seoWorkflow: 'Collez le Markdown existant, vérifiez l aperçu du document et copiez le résultat mis en forme. Les titres, paragraphes, listes, liens, citations, blocs de code et emphases sont traités localement.', seoFeatures: ['<strong>Sortie riche :</strong> copiez le HTML avec une version texte brut.', '<strong>Périmètre clair :</strong> la syntaxe Markdown prise en charge est documentée.', '<strong>Traitement local :</strong> votre brouillon reste dans le navigateur.', '<strong>Reprise pratique :</strong> votre dernier brouillon est restauré.'],
  ui: { labelKicker: 'Espace Markdown', labelInput: 'Source Markdown', labelPreview: 'Aperçu du texte riche', placeholderInput: 'Collez votre Markdown ici...', btnExample: 'Charger un exemple', btnClear: 'Effacer', btnCopy: 'Copier le texte riche', toastCopied: 'Texte riche copié !', toastCopyError: 'La copie a été bloquée. Sélectionnez l aperçu et copiez-le manuellement.', toastRestored: 'Votre dernier brouillon a été restauré.', emptyPreview: 'Votre document mis en forme apparaîtra ici.', labelHint: 'Prend en charge les structures Markdown courantes. Le HTML dangereux est échappé et tout est traité dans le navigateur.', labelBlocks: 'blocs', labelWords: 'mots', labelWarnings: 'alertes', warningMessage: 'Une partie du contenu a été échappée ou ne pouvait pas être traitée comme un lien sûr.', exampleMarkdown: '# Notes de version\n\nUne mise à jour **ciblée** avec un [lien vers le projet](https://example.com).\n\n- Conversion locale rapide\n- Sortie texte riche\n\n> Collez le résultat dans votre éditeur.\n\n```js\nconst pret = true;\n```' },
});
