import { createMarkdownToRichTextContent } from '../content';
import { getBibliography } from '../bibliography';

export const content = createMarkdownToRichTextContent({
  locale: 'id', slug: 'markdown-ke-teks-kaya', title: 'Konverter Markdown ke Teks Kaya: Salin HTML Berformat', description: 'Ubah Markdown menjadi teks kaya dengan pratinjau langsung dan HTML yang siap ditempel. Semua proses berjalan di browser.', bibliography: getBibliography('id'),
  faq: [
    { question: 'Apa yang dihasilkan konverter Markdown ke teks kaya ini?', answer: 'Alat ini mengubah Markdown yang didukung menjadi teks kaya semantik untuk diperiksa lalu ditempel ke editor, email, dokumen, atau CMS.' },
    { question: 'Fitur Markdown apa yang didukung?', answer: 'Judul, paragraf, penekanan, tautan, gambar, kutipan, daftar, kode sebaris, blok kode, dan garis horizontal didukung.' },
    { question: 'Mengapa menggunakan teks kaya, bukan Markdown?', answer: 'Banyak editor mempertahankan format saat ditempel, tetapi tidak menafsirkan sintaks Markdown. Alat ini menjembatani kedua format tersebut.' },
    { question: 'Apakah format yang ditempel akan sama di semua aplikasi?', answer: 'Editor teks kaya memiliki gaya sendiri dan dukungan HTML yang berbeda. Perbedaan visual kecil antar aplikasi adalah hal yang wajar.' },
  ],
  howTo: [{ name: 'Tempel Markdown', text: 'Tempel dokumen Markdown ke panel sumber.' }, { name: 'Periksa pratinjau', text: 'Tinjau halaman teks kaya dan strukturnya.' }, { name: 'Salin teks kaya', text: 'Salin hasil berformat lalu tempelkan ke dokumen, email, CMS, atau editor.' }],
  seoTitle: 'Ubah Markdown menjadi teks kaya yang siap ditempel', seoIntro: 'Markdown cocok untuk menulis dan mengelola versi, tetapi banyak editor email, dokumen, dan CMS mengharapkan teks kaya. Alat ini membuat versi HTML semantik dari Markdown Anda.', seoWorkflowTitle: 'Alur konversi yang ringkas', seoWorkflow: 'Tempel Markdown yang sudah Anda miliki, periksa pratinjau, lalu salin hasil berformat. Judul, paragraf, daftar, tautan, kutipan, kode, dan penekanan diproses secara lokal.', seoFeatures: ['<strong>Hasil kaya:</strong> salin HTML bersama cadangan teks biasa.', '<strong>Cakupan jelas:</strong> sintaks Markdown yang didukung dijelaskan.', '<strong>Proses lokal:</strong> draf Anda tetap berada di browser.', '<strong>Mudah dilanjutkan:</strong> draf terakhir dipulihkan saat kembali.'],
  ui: { labelKicker: 'Meja Markdown', labelInput: 'Sumber Markdown', labelPreview: 'Pratinjau teks kaya', placeholderInput: 'Tempel Markdown di sini...', btnExample: 'Muat contoh', btnClear: 'Hapus', btnCopy: 'Salin teks kaya', toastCopied: 'Teks kaya disalin!', toastCopyError: 'Penyalinan diblokir. Pilih pratinjau lalu salin secara manual.', toastRestored: 'Draf terakhir dipulihkan.', emptyPreview: 'Dokumen berformat Anda akan muncul di sini.', labelHint: 'Mendukung struktur Markdown umum. HTML yang tidak aman akan di-escape dan semua proses berjalan di browser.', labelBlocks: 'blok', labelWords: 'kata', labelWarnings: 'peringatan', warningMessage: 'Sebagian konten di-escape atau tidak dapat diperlakukan sebagai tautan aman.', exampleMarkdown: '# Catatan rilis\n\nPembaruan **terarah** dengan [tautan proyek](https://example.com).\n\n- Konversi lokal cepat\n- Hasil teks kaya\n\n> Tempel hasilnya ke editor Anda.\n\n```js\nconst siap = true;\n```' },
});
