import { createMarkdownToRichTextContent } from '../content';
import { getBibliography } from '../bibliography';

export const content = createMarkdownToRichTextContent({
  locale: 'it', slug: 'markdown-a-testo-ricco', title: 'Convertitore da Markdown a testo ricco: copia HTML formattato', description: 'Converti Markdown in testo ricco con anteprima live e HTML pronto da incollare. Tutto avviene nel browser.', bibliography: getBibliography('it'),
  faq: [
    { question: 'Che cosa produce questo convertitore da Markdown a testo ricco?', answer: "Trasforma il Markdown supportato in testo ricco semantico, da controllare e incollare in un editor, un'email, un documento o un CMS." },
    { question: 'Quali funzioni Markdown sono supportate?', answer: 'Sono supportati titoli, paragrafi, enfasi, collegamenti, immagini, citazioni, elenchi, codice in linea, blocchi di codice e righe orizzontali.' },
    { question: 'Perché usare il testo ricco invece del Markdown?', answer: 'Molti editor mantengono la formattazione quando incolli, ma non interpretano la sintassi Markdown. Questo strumento collega i due formati.' },
    { question: 'La formattazione incollata sarà identica in ogni app?', answer: 'Gli editor di testo ricco applicano stili propri e supportano elementi HTML diversi. Sono quindi possibili piccole differenze visive.' },
  ],
  howTo: [{ name: 'Incolla il Markdown', text: 'Incolla il documento Markdown nel pannello sorgente.' }, { name: "Controlla l'anteprima", text: 'Esamina la pagina in testo ricco e la sua struttura.' }, { name: 'Copia il testo ricco', text: "Copia il risultato formattato e incollalo nel documento, nell'email, nel CMS o nell'editor." }],
  seoTitle: 'Trasforma Markdown in testo ricco pronto da incollare', seoIntro: 'Markdown è ottimo per scrivere e gestire le versioni, ma molti editor di email, documenti e CMS richiedono testo ricco. Questo convertitore crea una versione HTML semantica del tuo Markdown.', seoWorkflowTitle: 'Un flusso di conversione essenziale', seoWorkflow: "Incolla il Markdown che hai già, controlla l'anteprima del documento e copia il risultato formattato. Titoli, paragrafi, elenchi, link, citazioni, codice ed enfasi vengono gestiti localmente.", seoFeatures: ["<strong>Output ricco:</strong> copia HTML con un'alternativa in testo semplice.", '<strong>Ambito chiaro:</strong> la sintassi Markdown supportata è documentata.', '<strong>Flusso locale:</strong> la bozza rimane nel browser.', "<strong>Ripresa pratica:</strong> l'ultima bozza viene ripristinata."],
  ui: { labelKicker: 'Spazio Markdown', labelInput: 'Sorgente Markdown', labelPreview: 'Anteprima del testo ricco', placeholderInput: 'Incolla qui il Markdown...', btnExample: 'Carica esempio', btnClear: 'Cancella', btnCopy: 'Copia testo ricco', toastCopied: 'Testo ricco copiato!', toastCopyError: "La copia è stata bloccata. Seleziona l'anteprima e copiala manualmente.", toastRestored: 'Ultima bozza ripristinata.', emptyPreview: 'Il documento formattato apparirà qui.', labelHint: "Supporta le strutture Markdown comuni. L'HTML non sicuro viene neutralizzato e tutto viene elaborato nel browser.", labelBlocks: 'blocchi', labelWords: 'parole', labelWarnings: 'avvisi', warningMessage: 'Parte del contenuto è stata neutralizzata o non poteva essere trattata come link sicuro.', exampleMarkdown: '# Note di rilascio\n\nUn aggiornamento **mirato** con un [link al progetto](https://example.com).\n\n- Conversione locale rapida\n- Output in testo ricco\n\n> Incolla il risultato nel tuo editor.\n\n```js\nconst pronto = true;\n```' },
});
