import { createMarkdownToRichTextContent } from '../content';
import { getBibliography } from '../bibliography';

export const content = createMarkdownToRichTextContent({
  locale: 'nl', slug: 'markdown-naar-rich-text', title: 'Markdown naar rich text converter: opgemaakte HTML kopiëren', description: 'Zet Markdown om in rich text met een live voorbeeld en HTML dat klaar is om te plakken. Alles gebeurt in je browser.', bibliography: getBibliography('nl'),
  faq: [
    { question: 'Wat maakt deze Markdown-naar-rich-textconverter?', answer: 'De converter zet ondersteunde Markdown om in semantisch opgemaakte rich text die je kunt controleren en plakken in een editor, e-mail, document of CMS.' },
    { question: 'Welke Markdown-functies worden ondersteund?', answer: "Koppen, alinea's, nadruk, links, afbeeldingen, citaten, genummerde en ongenummerde lijsten, inline code, codeblokken en horizontale lijnen worden ondersteund." },
    { question: 'Waarom rich text gebruiken in plaats van Markdown?', answer: 'Veel editors behouden opmaak bij het plakken, maar interpreteren Markdown-syntaxis niet. Deze tool overbrugt beide formaten.' },
    { question: 'Ziet de geplakte opmaak er overal hetzelfde uit?', answer: 'Rich-texteditors gebruiken eigen stijlen en ondersteunen verschillende HTML-elementen. Kleine visuele verschillen tussen apps zijn normaal.' },
  ],
  howTo: [{ name: 'Markdown plakken', text: 'Plak je Markdown-document in het bronpaneel.' }, { name: 'Voorbeeld controleren', text: 'Controleer de weergegeven rich-textpagina en de structuur.' }, { name: 'Rich text kopiëren', text: 'Kopieer het opgemaakte resultaat en plak het in je document, e-mail, CMS of editor.' }],
  seoTitle: 'Zet Markdown om in rich text die klaar is om te plakken', seoIntro: 'Markdown is uitstekend voor schrijven en versiebeheer, maar veel e-mailcomponisten, documenteditors en CMS-velden verwachten rich text. Deze tool maakt een semantische HTML-versie van je Markdown.', seoWorkflowTitle: 'Een eenvoudige conversieworkflow', seoWorkflow: "Plak je bestaande Markdown, controleer het documentvoorbeeld en kopieer het opgemaakte resultaat. Koppen, alinea's, lijsten, links, citaten, code en nadruk worden lokaal verwerkt.", seoFeatures: ['<strong>Rijke uitvoer:</strong> kopieer HTML met een tekstalternatief.', '<strong>Duidelijke reikwijdte:</strong> ondersteunde Markdown-syntaxis wordt beschreven.', '<strong>Lokale verwerking:</strong> je concept blijft in de browser.', '<strong>Praktisch hervatten:</strong> je laatste concept wordt hersteld.'],
  ui: { labelKicker: 'Markdown-werkruimte', labelInput: 'Markdown-bron', labelPreview: 'Rich-textvoorbeeld', placeholderInput: 'Plak hier je Markdown...', btnExample: 'Voorbeeld laden', btnClear: 'Wissen', btnCopy: 'Rich text kopiëren', toastCopied: 'Rich text gekopieerd!', toastCopyError: 'Kopiëren is geblokkeerd. Selecteer het voorbeeld en kopieer het handmatig.', toastRestored: 'Je laatste concept is hersteld.', emptyPreview: 'Je opgemaakte document verschijnt hier.', labelHint: 'Ondersteunt gangbare Markdown-structuren. Onveilige HTML wordt geneutraliseerd en alles wordt in je browser verwerkt.', labelBlocks: 'blokken', labelWords: 'woorden', labelWarnings: 'waarschuwingen', warningMessage: 'Een deel van de inhoud is geneutraliseerd of kon niet als veilige link worden behandeld.', exampleMarkdown: '# Release notes\n\nEen **gerichte** update met een [projectlink](https://example.com).\n\n- Snelle lokale conversie\n- Rijke klemborduitvoer\n\n> Plak het resultaat in je editor.\n\n```js\nconst klaar = true;\n```' },
});
