import { createMarkdownToRichTextContent } from '../content';
import { getBibliography } from '../bibliography';

export const content = createMarkdownToRichTextContent({
  locale: 'pl', slug: 'markdown-na-tekst-sformatowany', title: 'Konwerter Markdown na tekst sformatowany: kopiuj HTML', description: 'Konwertuj Markdown na tekst sformatowany z podglądem na żywo i kodem HTML gotowym do wklejenia. Wszystko działa w przeglądarce.', bibliography: getBibliography('pl'),
  faq: [
    { question: 'Co tworzy ten konwerter Markdown na tekst sformatowany?', answer: 'Zamienia obsługiwany Markdown na semantyczny tekst sformatowany, który możesz sprawdzić i wkleić do edytora, wiadomości e-mail, dokumentu lub CMS-a.' },
    { question: 'Jakie funkcje Markdown są obsługiwane?', answer: 'Obsługiwane są nagłówki, akapity, wyróżnienia, linki, obrazy, cytaty, listy numerowane i punktowane, kod w tekście, bloki kodu oraz linie poziome.' },
    { question: 'Dlaczego używać tekstu sformatowanego zamiast Markdown?', answer: 'Wiele edytorów zachowuje formatowanie podczas wklejania, ale nie interpretuje składni Markdown. To narzędzie łączy oba formaty.' },
    { question: 'Czy wklejone formatowanie będzie wszędzie takie samo?', answer: 'Edytory tekstu sformatowanego używają własnych stylów i obsługują różne elementy HTML. Niewielkie różnice wizualne między aplikacjami są normalne.' },
  ],
  howTo: [{ name: 'Wklej Markdown', text: 'Wklej dokument Markdown do panelu źródłowego.' }, { name: 'Sprawdź podgląd', text: 'Przejrzyj wyrenderowaną stronę tekstu sformatowanego i jej strukturę.' }, { name: 'Skopiuj tekst sformatowany', text: 'Skopiuj sformatowany wynik i wklej go do dokumentu, wiadomości, CMS-a lub edytora.' }],
  seoTitle: 'Konwertuj Markdown na tekst sformatowany gotowy do wklejenia', seoIntro: 'Markdown świetnie nadaje się do pisania i kontroli wersji, ale wiele edytorów poczty, dokumentów i pól CMS oczekuje tekstu sformatowanego. To narzędzie tworzy semantyczną wersję HTML z Twojego Markdownu.', seoWorkflowTitle: 'Prosty przebieg konwersji', seoWorkflow: 'Wklej istniejący Markdown, sprawdź podgląd dokumentu i skopiuj sformatowany wynik. Nagłówki, akapity, listy, linki, cytaty, kod i wyróżnienia są przetwarzane lokalnie.', seoFeatures: ['<strong>Sformatowany wynik:</strong> kopiuj HTML z wersją tekstową.', '<strong>Jasny zakres:</strong> obsługiwana składnia Markdown jest opisana.', '<strong>Praca lokalna:</strong> szkic pozostaje w przeglądarce.', '<strong>Łatwy powrót:</strong> ostatni szkic jest przywracany.'],
  ui: { labelKicker: 'Przestrzeń Markdown', labelInput: 'Źródło Markdown', labelPreview: 'Podgląd tekstu sformatowanego', placeholderInput: 'Wklej tutaj Markdown...', btnExample: 'Wczytaj przykład', btnClear: 'Wyczyść', btnCopy: 'Kopiuj tekst sformatowany', toastCopied: 'Tekst sformatowany skopiowany!', toastCopyError: 'Kopiowanie zostało zablokowane. Zaznacz podgląd i skopiuj go ręcznie.', toastRestored: 'Przywrócono ostatni szkic.', emptyPreview: 'Sformatowany dokument pojawi się tutaj.', labelHint: 'Obsługuje typowe struktury Markdown. Niebezpieczny HTML jest neutralizowany, a całość działa w przeglądarce.', labelBlocks: 'bloki', labelWords: 'słowa', labelWarnings: 'ostrzeżenia', warningMessage: 'Część treści została zneutralizowana lub nie mogła zostać potraktowana jako bezpieczny link.', exampleMarkdown: '# Informacje o wydaniu\n\nSkupiona **aktualizacja** z [linkiem do projektu](https://example.com).\n\n- Szybka konwersja lokalna\n- Sformatowany wynik\n\n> Wklej wynik do swojego edytora.\n\n```js\nconst gotowe = true;\n```' },
});
