import { createMarkdownToRichTextContent } from '../content';
import { getBibliography } from '../bibliography';

export const content = createMarkdownToRichTextContent({
  locale: 'pt', slug: 'markdown-para-texto-formatado', title: 'Conversor de Markdown para texto formatado: copie HTML', description: 'Converta Markdown em texto formatado com pré-visualização ao vivo e HTML pronto para colar. Tudo acontece no navegador.', bibliography: getBibliography('pt'),
  faq: [
    { question: 'O que este conversor de Markdown para texto formatado produz?', answer: 'Ele transforma o Markdown compatível em texto formatado semântico para você revisar e colar em um editor, e-mail, documento ou CMS.' },
    { question: 'Quais recursos de Markdown são compatíveis?', answer: 'São compatíveis títulos, parágrafos, ênfase, links, imagens, citações, listas numeradas e com marcadores, código em linha, blocos de código e linhas horizontais.' },
    { question: 'Por que usar texto formatado em vez de Markdown?', answer: 'Muitos editores preservam a formatação ao colar, mas não interpretam a sintaxe Markdown. Esta ferramenta conecta os dois formatos.' },
    { question: 'A formatação colada ficará igual em todos os aplicativos?', answer: 'Editores de texto formatado usam estilos próprios e oferecem suporte a elementos HTML diferentes. Pequenas diferenças visuais são esperadas.' },
  ],
  howTo: [{ name: 'Cole o Markdown', text: 'Cole o documento Markdown no painel de origem.' }, { name: 'Confira a pré-visualização', text: 'Revise a página de texto formatado e sua estrutura.' }, { name: 'Copie o texto formatado', text: 'Copie o resultado formatado e cole-o no documento, e-mail, CMS ou editor.' }],
  seoTitle: 'Converta Markdown em texto formatado pronto para colar', seoIntro: 'Markdown é ótimo para escrever e controlar versões, mas muitos editores de e-mail, documentos e campos de CMS esperam texto formatado. Esta ferramenta cria uma versão HTML semântica do seu Markdown.', seoWorkflowTitle: 'Um fluxo de conversão direto', seoWorkflow: 'Cole o Markdown que você já tem, confira a pré-visualização do documento e copie o resultado formatado. Títulos, parágrafos, listas, links, citações, código e ênfase são processados localmente.', seoFeatures: ['<strong>Saída formatada:</strong> copie HTML com uma alternativa em texto simples.', '<strong>Escopo claro:</strong> a sintaxe Markdown compatível é documentada.', '<strong>Processamento local:</strong> seu rascunho fica no navegador.', '<strong>Retomada prática:</strong> o último rascunho é restaurado.'],
  ui: { labelKicker: 'Mesa Markdown', labelInput: 'Origem Markdown', labelPreview: 'Pré-visualização do texto formatado', placeholderInput: 'Cole o Markdown aqui...', btnExample: 'Carregar exemplo', btnClear: 'Limpar', btnCopy: 'Copiar texto formatado', toastCopied: 'Texto formatado copiado!', toastCopyError: 'A cópia foi bloqueada. Selecione a pré-visualização e copie-a manualmente.', toastRestored: 'Seu último rascunho foi restaurado.', emptyPreview: 'Seu documento formatado aparecerá aqui.', labelHint: 'Compatível com estruturas Markdown comuns. HTML inseguro é neutralizado e todo o processamento ocorre no navegador.', labelBlocks: 'blocos', labelWords: 'palavras', labelWarnings: 'avisos', warningMessage: 'Parte do conteúdo foi neutralizada ou não pôde ser tratada como um link seguro.', exampleMarkdown: '# Notas da versão\n\nUma atualização **focada** com um [link do projeto](https://example.com).\n\n- Conversão local rápida\n- Saída em texto formatado\n\n> Cole o resultado no seu editor.\n\n```js\nconst pronto = true;\n```' },
});
