import { createMarkdownToRichTextContent } from '../content';
import { getBibliography } from '../bibliography';

export const content = createMarkdownToRichTextContent({
  locale: 'sv', slug: 'markdown-till-formaterad-text', title: 'Konvertera Markdown till formaterad text: kopiera HTML', description: 'Konvertera Markdown till formaterad text med direkt förhandsvisning och HTML som kan klistras in. Allt sker i webbläsaren.', bibliography: getBibliography('sv'),
  faq: [
    { question: 'Vad skapar den här Markdown-konverteraren?', answer: 'Den omvandlar Markdown som stöds till semantiskt formaterad text som du kan granska och klistra in i en editor, ett mejl, ett dokument eller ett CMS.' },
    { question: 'Vilka Markdown-funktioner stöds?', answer: 'Rubriker, stycken, betoning, länkar, bilder, citat, numrerade och punktade listor, inlinekod, kodblock och horisontella linjer stöds.' },
    { question: 'Varför använda formaterad text i stället för Markdown?', answer: 'Många editorer behåller formatering när du klistrar in, men tolkar inte Markdown-syntax. Det här verktyget kopplar ihop formaten.' },
    { question: 'Ser den inklistrade formateringen likadan ut överallt?', answer: 'Editorer för formaterad text använder egna stilar och stöder olika HTML-element. Små visuella skillnader mellan appar är normala.' },
  ],
  howTo: [{ name: 'Klistra in Markdown', text: 'Klistra in Markdown-dokumentet i källpanelen.' }, { name: 'Kontrollera förhandsvisningen', text: 'Granska den formaterade sidan och dess struktur.' }, { name: 'Kopiera formaterad text', text: 'Kopiera resultatet och klistra in det i dokumentet, mejlet, CMS:et eller editorn.' }],
  seoTitle: 'Gör om Markdown till formaterad text som är klar att klistra in', seoIntro: 'Markdown är utmärkt för skrivande och versionshantering, men många mejlverktyg, dokumenteditorer och CMS-fält förväntar sig formaterad text. Det här verktyget skapar en semantisk HTML-version av din Markdown.', seoWorkflowTitle: 'Ett enkelt arbetsflöde', seoWorkflow: 'Klistra in Markdown, kontrollera dokumentets förhandsvisning och kopiera det formaterade resultatet. Rubriker, stycken, listor, länkar, citat, kod och betoning hanteras lokalt.', seoFeatures: ['<strong>Formaterat resultat:</strong> kopiera HTML med en textversion som reserv.', '<strong>Tydlig omfattning:</strong> den Markdown-syntax som stöds är dokumenterad.', '<strong>Lokal hantering:</strong> utkastet stannar i webbläsaren.', '<strong>Enkelt att fortsätta:</strong> det senaste utkastet återställs.'],
  ui: { labelKicker: 'Markdown-arbetsyta', labelInput: 'Markdown-källa', labelPreview: 'Förhandsvisning av formaterad text', placeholderInput: 'Klistra in Markdown här...', btnExample: 'Ladda exempel', btnClear: 'Rensa', btnCopy: 'Kopiera formaterad text', toastCopied: 'Formaterad text kopierad!', toastCopyError: 'Kopieringen blockerades. Markera förhandsvisningen och kopiera den manuellt.', toastRestored: 'Det senaste utkastet har återställts.', emptyPreview: 'Det formaterade dokumentet visas här.', labelHint: 'Stöder vanliga Markdown-strukturer. Osäker HTML kodas och allt behandlas i webbläsaren.', labelBlocks: 'block', labelWords: 'ord', labelWarnings: 'varningar', warningMessage: 'En del av innehållet kodades eller kunde inte behandlas som en säker länk.', exampleMarkdown: '# Versionsanteckningar\n\nEn **fokuserad** uppdatering med en [projektlänk](https://example.com).\n\n- Snabb lokal konvertering\n- Formaterat resultat\n\n> Klistra in resultatet i din editor.\n\n```js\nconst klar = true;\n```' },
});
