import { createMarkdownToRichTextContent } from '../content';
import { getBibliography } from '../bibliography';

export const content = createMarkdownToRichTextContent({
  locale: 'tr', slug: 'markdowni-zengin-metne-donustur', title: "Markdown'ı Zengin Metne Dönüştür: Biçimli HTML'yi Kopyala", description: "Markdown'ı canlı önizleme ve yapıştırmaya hazır HTML ile zengin metne dönüştürün. Her şey tarayıcınızda gerçekleşir.", bibliography: getBibliography('tr'),
  faq: [
    { question: "Bu Markdown'dan zengin metne dönüştürücü ne üretir?", answer: "Desteklenen Markdown'ı anlamsal zengin metne dönüştürür; sonucu inceleyip bir düzenleyiciye, e-postaya, belgeye veya CMS'e yapıştırabilirsiniz." },
    { question: 'Hangi Markdown özellikleri destekleniyor?', answer: 'Başlıklar, paragraflar, vurgu, bağlantılar, görseller, alıntılar, numaralı ve madde işaretli listeler, satır içi kod, kod blokları ve yatay çizgiler desteklenir.' },
    { question: 'Markdown yerine neden zengin metin kullanılmalı?', answer: 'Birçok düzenleyici yapıştırma sırasında biçimi korur ancak Markdown söz dizimini yorumlamaz. Bu araç iki format arasında köprü kurar.' },
    { question: 'Yapıştırılan biçim her uygulamada aynı mı görünür?', answer: 'Zengin metin düzenleyicileri kendi stillerini kullanır ve farklı HTML özelliklerini destekler. Uygulamalar arasında küçük görsel farklar normaldir.' },
  ],
  howTo: [{ name: "Markdown'ı yapıştırın", text: 'Markdown belgesini kaynak paneline yapıştırın.' }, { name: 'Önizlemeyi kontrol edin', text: 'Oluşturulan zengin metin sayfasını ve yapısını inceleyin.' }, { name: 'Zengin metni kopyalayın', text: "Biçimli sonucu kopyalayarak belgenize, e-postanıza, CMS'inize veya düzenleyicinize yapıştırın." }],
  seoTitle: "Markdown'ı yapıştırmaya hazır zengin metne dönüştürün", seoIntro: "Markdown yazmak ve sürüm takibi için harikadır; ancak birçok e-posta oluşturucusu, belge düzenleyicisi ve CMS alanı zengin metin bekler. Bu araç Markdown'ınızın anlamsal bir HTML sürümünü oluşturur.", seoWorkflowTitle: 'Basit bir dönüştürme akışı', seoWorkflow: "Elinizdeki Markdown'ı yapıştırın, belge önizlemesini inceleyin ve biçimli sonucu kopyalayın. Başlıklar, paragraflar, listeler, bağlantılar, alıntılar, kod ve vurgu yerel olarak işlenir.", seoFeatures: ['<strong>Zengin çıktı:</strong> düz metin yedeğiyle birlikte HTML kopyalayın.', '<strong>Net kapsam:</strong> desteklenen Markdown söz dizimi açıklanır.', '<strong>Yerel işlem:</strong> taslağınız tarayıcıda kalır.', '<strong>Kolay devam:</strong> son taslağınız geri yüklenir.'],
  ui: { labelKicker: 'Markdown çalışma alanı', labelInput: 'Markdown kaynağı', labelPreview: 'Zengin metin önizlemesi', placeholderInput: "Markdown'ı buraya yapıştırın...", btnExample: 'Örnek yükle', btnClear: 'Temizle', btnCopy: 'Zengin metni kopyala', toastCopied: 'Zengin metin kopyalandı!', toastCopyError: 'Kopyalama engellendi. Önizlemeyi seçip elle kopyalayın.', toastRestored: 'Son taslağınız geri yüklendi.', emptyPreview: 'Biçimli belgeniz burada görünecek.', labelHint: 'Yaygın Markdown yapılarını destekler. Güvenli olmayan HTML kaçışlanır ve tüm işlemler tarayıcınızda yapılır.', labelBlocks: 'blok', labelWords: 'kelime', labelWarnings: 'uyarı', warningMessage: 'İçeriğin bir kısmı kaçışlandı veya güvenli bağlantı olarak işlenemedi.', exampleMarkdown: '# Sürüm notları\n\n[Proje bağlantısı](https://example.com) içeren **odaklı** bir güncelleme.\n\n- Hızlı yerel dönüştürme\n- Zengin metin çıktısı\n\n> Sonucu düzenleyicinize yapıştırın.\n\n```js\nconst hazir = true;\n```' },
});
