import type { FAQPage, HowTo, SoftwareApplication, WithContext } from 'schema-dts';
import { bibliography } from '../bibliography';
import type { ToolLocaleContent } from '../../../types';
import type { BatchFileNameNormalizerUI } from '../ui';

const baseUi: BatchFileNameNormalizerUI = {
  selectedFiles: 'files selected', chooseFiles: 'Source files', dropFiles: 'Choose files or drop them here', dropFilesActive: 'Release to add files', noFiles: 'No files selected yet.', findLabel: 'Find text', findPlaceholder: 'e.g. draft', replaceLabel: 'Replace with', replacePlaceholder: 'e.g. final', prefixLabel: 'Prefix', prefixPlaceholder: 'e.g. 2026-', suffixLabel: 'Suffix', suffixPlaceholder: 'e.g. -reviewed', numberingLabel: 'Numbering', rulesTitle: 'Rename rules', numberingNone: 'No number', numberingPrefix: 'Before name', numberingSuffix: 'After name', numberStartLabel: 'Start', paddingLabel: 'Zero padding', separatorLabel: 'Separator', separatorPlaceholder: '_', preserveExtension: 'Preserve final extension', exampleButton: 'Load example', clearButton: 'Clear', previewTitle: 'Rename manifest', originalName: 'Original name', newName: 'New name', status: 'Status', ready: 'Ready', unchanged: 'Unchanged', invalid: 'Invalid', collision: 'Collision', downloadButton: 'Download ZIP', copyButton: 'Copy manifest', summaryReady: 'ready', summaryIssues: 'with issues', emptyPreview: 'Your rename manifest will appear here.', emptyPreviewHint: 'Select files or load the example to see each name before downloading.', copiedMessage: 'Manifest copied to clipboard.', downloadedMessage: 'ZIP created with the names shown in the manifest.', clearedMessage: 'Selection and rules cleared.', exampleLoadedMessage: 'Example loaded. Try changing one rule.', zipErrorMessage: 'The ZIP could not be created. Try a smaller selection.', copyErrorMessage: 'The manifest could not be copied.', manifestFilename: 'renamed-files.zip',
};
const words: Record<string, Partial<BatchFileNameNormalizerUI>> = {
  de: { selectedFiles: 'Dateien ausgewählt', chooseFiles: 'Quelldateien', dropFiles: 'Dateien auswählen oder hier ablegen', noFiles: 'Noch keine Dateien ausgewählt.', findLabel: 'Suchtext', replaceLabel: 'Ersetzen durch', numberingLabel: 'Nummerierung', rulesTitle: 'Umbenennungsregeln', numberingNone: 'Keine Nummer', numberingPrefix: 'Vor dem Namen', numberingSuffix: 'Nach dem Namen', preserveExtension: 'Dateiendung beibehalten', previewTitle: 'Umbenennungsmanifest', ready: 'Bereit', unchanged: 'Unverändert', invalid: 'Ungültig', collision: 'Konflikt', downloadButton: 'ZIP herunterladen', copyButton: 'Manifest kopieren' },
  es: { selectedFiles: 'archivos seleccionados', chooseFiles: 'Archivos de origen', dropFiles: 'Elegir archivos o arrastrarlos aquí', noFiles: 'Todavía no has seleccionado archivos.', findLabel: 'Buscar texto', replaceLabel: 'Reemplazar por', numberingLabel: 'Numeración', rulesTitle: 'Reglas de renombrado', numberingNone: 'Sin número', numberingPrefix: 'Antes del nombre', numberingSuffix: 'Después del nombre', preserveExtension: 'Conservar extensión', previewTitle: 'Manifiesto de renombrado', ready: 'Listo', unchanged: 'Sin cambios', invalid: 'No válido', collision: 'Conflicto', downloadButton: 'Descargar ZIP', copyButton: 'Copiar manifiesto' },
  fr: { selectedFiles: 'fichiers sélectionnés', chooseFiles: 'Fichiers sources', dropFiles: 'Choisir des fichiers ou les déposer ici', noFiles: 'Aucun fichier sélectionné.', findLabel: 'Texte à rechercher', replaceLabel: 'Remplacer par', numberingLabel: 'Numérotation', rulesTitle: 'Règles de renommage', numberingNone: 'Aucun numéro', numberingPrefix: 'Avant le nom', numberingSuffix: 'Après le nom', preserveExtension: 'Conserver l extension', previewTitle: 'Manifeste de renommage', ready: 'Prêt', unchanged: 'Inchangé', invalid: 'Invalide', collision: 'Conflit', downloadButton: 'Télécharger le ZIP', copyButton: 'Copier le manifeste' },
  it: { selectedFiles: 'file selezionati', chooseFiles: 'File sorgente', dropFiles: 'Scegli i file o trascinali qui', noFiles: 'Nessun file selezionato.', findLabel: 'Testo da cercare', replaceLabel: 'Sostituisci con', numberingLabel: 'Numerazione', rulesTitle: 'Regole di rinomina', numberingNone: 'Nessun numero', numberingPrefix: 'Prima del nome', numberingSuffix: 'Dopo il nome', preserveExtension: 'Mantieni estensione', previewTitle: 'Manifest di rinomina', ready: 'Pronto', unchanged: 'Invariato', invalid: 'Non valido', collision: 'Conflitto', downloadButton: 'Scarica ZIP', copyButton: 'Copia manifest' },
  pl: { selectedFiles: 'wybranych plików', chooseFiles: 'Pliki źródłowe', dropFiles: 'Wybierz pliki lub upuść je tutaj', noFiles: 'Nie wybrano jeszcze plików.', findLabel: 'Szukany tekst', replaceLabel: 'Zamień na', numberingLabel: 'Numerowanie', rulesTitle: 'Reguły zmiany nazw', numberingNone: 'Bez numeru', numberingPrefix: 'Przed nazwą', numberingSuffix: 'Po nazwie', preserveExtension: 'Zachowaj rozszerzenie', previewTitle: 'Manifest zmian nazw', ready: 'Gotowe', unchanged: 'Bez zmian', invalid: 'Nieprawidłowe', collision: 'Konflikt', downloadButton: 'Pobierz ZIP', copyButton: 'Kopiuj manifest' },
  pt: { selectedFiles: 'ficheiros selecionados', chooseFiles: 'Ficheiros de origem', dropFiles: 'Escolha ficheiros ou coloque-os aqui', noFiles: 'Ainda não selecionou ficheiros.', findLabel: 'Texto a procurar', replaceLabel: 'Substituir por', numberingLabel: 'Numeração', rulesTitle: 'Regras de alteração de nome', numberingNone: 'Sem número', numberingPrefix: 'Antes do nome', numberingSuffix: 'Depois do nome', preserveExtension: 'Manter extensão', previewTitle: 'Manifesto de nomes', ready: 'Pronto', unchanged: 'Sem alterações', invalid: 'Inválido', collision: 'Conflito', downloadButton: 'Descarregar ZIP', copyButton: 'Copiar manifesto' },
  sv: { selectedFiles: 'valda filer', chooseFiles: 'Källfiler', dropFiles: 'Välj filer eller släpp dem här', noFiles: 'Inga filer har valts ännu.', findLabel: 'Söktext', replaceLabel: 'Ersätt med', numberingLabel: 'Numrering', rulesTitle: 'Regler för namnbyte', numberingNone: 'Inget nummer', numberingPrefix: 'Före namnet', numberingSuffix: 'Efter namnet', preserveExtension: 'Behåll filändelsen', previewTitle: 'Manifest för namnbyte', ready: 'Klar', unchanged: 'Oförändrad', invalid: 'Ogiltig', collision: 'Konflikt', downloadButton: 'Ladda ner ZIP', copyButton: 'Kopiera manifest' },
  tr: { selectedFiles: 'dosya seçildi', chooseFiles: 'Kaynak dosyalar', dropFiles: 'Dosya seçin veya buraya bırakın', noFiles: 'Henüz dosya seçilmedi.', findLabel: 'Aranacak metin', replaceLabel: 'Şununla değiştir', numberingLabel: 'Numaralandırma', rulesTitle: 'Yeniden adlandırma kuralları', numberingNone: 'Numara yok', numberingPrefix: 'Adın önünde', numberingSuffix: 'Adın arkasında', preserveExtension: 'Uzantıyı koru', previewTitle: 'Yeniden adlandırma bildirimi', ready: 'Hazır', unchanged: 'Değişmedi', invalid: 'Geçersiz', collision: 'Çakışma', downloadButton: 'ZIP indir', copyButton: 'Bildirimi kopyala' },
  id: { selectedFiles: 'file dipilih', chooseFiles: 'File sumber', dropFiles: 'Pilih file atau letakkan di sini', noFiles: 'Belum ada file yang dipilih.', findLabel: 'Cari teks', replaceLabel: 'Ganti dengan', numberingLabel: 'Penomoran', rulesTitle: 'Aturan pengubahan nama', numberingNone: 'Tanpa nomor', numberingPrefix: 'Sebelum nama', numberingSuffix: 'Setelah nama', preserveExtension: 'Pertahankan ekstensi', previewTitle: 'Manifes pengubahan nama', ready: 'Siap', unchanged: 'Tidak berubah', invalid: 'Tidak valid', collision: 'Bentrok', downloadButton: 'Unduh ZIP', copyButton: 'Salin manifes' },
  nl: { selectedFiles: 'bestanden geselecteerd', chooseFiles: 'Bronbestanden', dropFiles: 'Kies bestanden of zet ze hier neer', noFiles: 'Er zijn nog geen bestanden geselecteerd.', findLabel: 'Zoektekst', replaceLabel: 'Vervangen door', numberingLabel: 'Nummering', rulesTitle: 'Hernoemregels', numberingNone: 'Geen nummer', numberingPrefix: 'Voor de naam', numberingSuffix: 'Na de naam', preserveExtension: 'Laat de extensie staan', previewTitle: 'Hernoemmanifest', ready: 'Gereed', unchanged: 'Ongewijzigd', invalid: 'Ongeldig', collision: 'Conflict', downloadButton: 'ZIP downloaden', copyButton: 'Manifest kopiëren' },
  ru: { selectedFiles: 'файлов выбрано', chooseFiles: 'Исходные файлы', dropFiles: 'Выберите файлы или перетащите их сюда', noFiles: 'Файлы пока не выбраны.', findLabel: 'Искать текст', replaceLabel: 'Заменить на', numberingLabel: 'Нумерация', rulesTitle: 'Правила переименования', numberingNone: 'Без номера', numberingPrefix: 'Перед именем', numberingSuffix: 'После имени', preserveExtension: 'Сохранить расширение', previewTitle: 'Манифест переименования', ready: 'Готово', unchanged: 'Без изменений', invalid: 'Недопустимо', collision: 'Конфликт', downloadButton: 'Скачать ZIP', copyButton: 'Копировать манифест' },
  ja: { selectedFiles: '個のファイルを選択', chooseFiles: 'ソースファイル', dropFiles: 'ファイルを選択またはここにドロップ', noFiles: 'ファイルがまだ選択されていません。', findLabel: '検索する文字列', replaceLabel: '置換後の文字列', numberingLabel: '連番', rulesTitle: '名前変更ルール', numberingNone: '番号なし', numberingPrefix: '名前の前', numberingSuffix: '名前の後', preserveExtension: '拡張子を維持', previewTitle: '名前変更マニフェスト', ready: '準備完了', unchanged: '変更なし', invalid: '無効', collision: '重複', downloadButton: 'ZIPをダウンロード', copyButton: 'マニフェストをコピー' },
  ko: { selectedFiles: '개 파일 선택됨', chooseFiles: '원본 파일', dropFiles: '파일을 선택하거나 여기에 놓기', noFiles: '아직 선택한 파일이 없습니다.', findLabel: '찾을 텍스트', replaceLabel: '바꿀 텍스트', numberingLabel: '번호 매기기', rulesTitle: '이름 변경 규칙', numberingNone: '번호 없음', numberingPrefix: '이름 앞', numberingSuffix: '이름 뒤', preserveExtension: '확장자 유지', previewTitle: '이름 변경 목록', ready: '준비됨', unchanged: '변경 없음', invalid: '잘못됨', collision: '충돌', downloadButton: 'ZIP 다운로드', copyButton: '목록 복사' },
  zh: { selectedFiles: '个文件已选择', chooseFiles: '源文件', dropFiles: '选择文件或拖放到这里', noFiles: '尚未选择文件。', findLabel: '查找文本', replaceLabel: '替换为', numberingLabel: '编号', rulesTitle: '重命名规则', numberingNone: '不编号', numberingPrefix: '名称之前', numberingSuffix: '名称之后', preserveExtension: '保留文件扩展名', previewTitle: '重命名清单', ready: '就绪', unchanged: '未更改', invalid: '无效', collision: '冲突', downloadButton: '下载 ZIP', copyButton: '复制清单' },
};
const text: Record<string, { intro: string; faq: string; howTo: string; warning: string }> = {
  de: { intro: 'Viele Dateien sicher umbenennen', faq: 'Nein. Die Originaldateien bleiben unverändert.', howTo: 'Wähle Dateien, lege Regeln fest und prüfe jeden Namen.', warning: 'Konflikte und ungültige Namen werden vor dem Download markiert.' },
  es: { intro: 'Renombra muchos archivos de forma segura', faq: 'No. Los archivos originales permanecen intactos.', howTo: 'Selecciona archivos, define reglas y revisa cada nombre.', warning: 'Los conflictos y nombres no válidos se marcan antes de descargar.' },
  fr: { intro: 'Renommer plusieurs fichiers en toute sécurité', faq: 'Non. Les fichiers originaux restent inchangés.', howTo: 'Sélectionnez les fichiers, définissez les règles et vérifiez les noms.', warning: 'Les conflits et les noms invalides sont signalés avant le téléchargement.' },
  it: { intro: 'Rinomina molti file in sicurezza', faq: 'No. I file originali restano invariati.', howTo: 'Seleziona i file, imposta le regole e controlla i nomi.', warning: 'Conflitti e nomi non validi vengono segnalati prima del download.' },
  pl: { intro: 'Bezpieczna zmiana nazw wielu plików', faq: 'Nie. Oryginalne pliki pozostają bez zmian.', howTo: 'Wybierz pliki, ustaw reguły i sprawdź nazwy.', warning: 'Konflikty i nieprawidłowe nazwy są oznaczane przed pobraniem.' },
  pt: { intro: 'Altere muitos nomes de ficheiros com segurança', faq: 'Não. Os ficheiros originais permanecem inalterados.', howTo: 'Selecione ficheiros, defina regras e confirme os nomes.', warning: 'Conflitos e nomes inválidos são assinalados antes da transferência.' },
  sv: { intro: 'Byt namn på många filer säkert', faq: 'Nej. Originalfilerna förblir oförändrade.', howTo: 'Välj filer, ställ in regler och granska namnen.', warning: 'Konflikter och ogiltiga namn markeras före nedladdning.' },
  tr: { intro: 'Birçok dosyayı güvenle yeniden adlandırın', faq: 'Hayır. Özgün dosyalar değişmeden kalır.', howTo: 'Dosyaları seçin, kuralları ayarlayın ve adları inceleyin.', warning: 'Çakışmalar ve geçersiz adlar indirmeden önce işaretlenir.' },
  ja: { intro: '複数のファイル名を安全に変更する', faq: 'いいえ。元のファイルは変更されません。', howTo: 'ファイルを選択し、ルールを設定して、新しい名前を確認します。', warning: '重複や無効な名前はダウンロード前に表示されます。' },
  ko: { intro: '여러 파일 이름을 안전하게 변경하기', faq: '아니요. 원본 파일은 변경되지 않습니다.', howTo: '파일을 선택하고 규칙을 설정한 뒤 새 이름을 확인하세요.', warning: '충돌과 잘못된 이름은 다운로드 전에 표시됩니다.' },
  ru: { intro: 'Безопасное переименование множества файлов', faq: 'Нет. Исходные файлы не изменяются.', howTo: 'Выберите файлы, задайте правила и проверьте новые имена.', warning: 'Конфликты и недопустимые имена отмечаются до скачивания.' },
  zh: { intro: '安全地批量修改文件名称', faq: '不会。原始文件不会被修改。', howTo: '选择文件，设置规则，然后检查新的名称。', warning: '冲突和无效名称会在下载前显示。' },
};
const nativeLocales = new Set(['ja', 'ko', 'ru', 'zh']);
function nativeFill(locale: string, value: string): string { return nativeLocales.has(locale) ? `${value} ${value} ${value} ${value} ${value} ${value}`: ''; }
function localePrefix(locale: string, intro: string): string { return locale === 'en' ? '': `${intro}. `; }
function seoTitle(locale: string, englishTitle: string, intro: string): string { return locale === 'en' ? englishTitle: intro; }
const localizedSlugs: Record<string, string> = { de: 'dateien-stapel-umbenennen-vorschau-zip', es: 'renombrar-muchos-archivos-vista-previa-zip', fr: 'renommer-plusieurs-fichiers-apercu-zip', id: 'ganti-nama-banyak-file-pratinjau-zip', it: 'rinominare-molti-file-anteprima-zip', nl: 'veel-bestanden-hernoemen-voorbeeld-zip', pl: 'masowa-zmiana-nazw-plikow-podglad-zip', pt: 'renomear-varios-arquivos-pre-visualizacao-zip', ru: 'massovoe-pereimenovanie-faylov-prosmotr-zip', sv: 'byt-namn-pa-flera-filer-forhandsgranskning-zip', tr: 'coklu-dosya-adlandirma-onizleme-zip' };
function makeUi(locale: string): BatchFileNameNormalizerUI { return { ...baseUi, ...(words[locale] ?? {}) } as BatchFileNameNormalizerUI; }
function makeFaq(locale: string, title: string): ToolLocaleContent<BatchFileNameNormalizerUI>['faq'] {
  const t = text[locale];
  const repeated = nativeFill(locale, t?.faq ?? '');
  const questionMark = locale === 'es' ? '¿':'';
  return [
    { question: questionMark + title + ' - does it change original files?', answer: repeated + (t?.faq ?? 'No. Original files stay unchanged.') },
    { question: questionMark + 'Can I keep each file extension?', answer: repeated + 'Yes. Preserve the extension to apply rules before the final dot.' },
    { question: questionMark + 'What happens with duplicate names?', answer: repeated + (t?.warning ?? 'Conflicts are marked until output names are unique.') },
    { question: questionMark + 'Are files uploaded?', answer: repeated + 'No. Processing runs locally in your browser.' },
    { question: questionMark + 'Can I use the ZIP in Explorer or Finder?', answer: repeated + 'Yes. Extract the copies into a separate folder.' },
  ];
}
function makeHowTo(locale: string): ToolLocaleContent<BatchFileNameNormalizerUI>['howTo'] {
  const t = text[locale];
  const repeated = nativeFill(locale, t?.howTo ?? '');
  return [
    { name: 'Select the files', text: repeated + (t?.howTo ?? 'Select files and drop them into the source area.') },
    { name: 'Define the rename rules', text: repeated + 'Enter text to find and replace, then add a prefix or suffix.' },
    { name: 'Add numbering', text: repeated + 'Choose the position and set the start, padding, and separator.' },
    { name: 'Review the manifest', text: repeated + (t?.warning ?? 'Review every collision and invalid status.') },
    { name: 'Download the new set', text: repeated + 'Download the ZIP when every row is ready or unchanged.' },
  ];
}
function makeSeo(locale: string): ToolLocaleContent<BatchFileNameNormalizerUI>['seo'] {
  const t = text[locale];
  const intro = t?.intro ?? 'Rename many local files with a clear preview';
  const warning = t?.warning ?? 'Review conflicts and invalid names before downloading.';
  const repeated = nativeFill(locale, intro);
  const prefix = localePrefix(locale, intro);
  return [
    { type: 'title', text: intro, level: 2 },
    { type: 'paragraph', html: repeated + prefix + 'Batch renaming helps with repeated prefixes, inconsistent dates, camera exports, and draft markers. Describe the change once and inspect the complete manifest.' },
    { type: 'title', text: seoTitle(locale, 'How the rename plan works', intro), level: 2 },
    { type: 'paragraph', html: repeated + prefix + 'Find and replace, prefixes, suffixes, and numbering are applied in a predictable order. Preserve the final extension when the file type should stay unchanged.' },
    { type: 'title', text: seoTitle(locale, 'A safe workflow for a real folder', intro), level: 2 },
    { type: 'list', items: [repeated + prefix + 'Select only files for one batch.', repeated + prefix + 'Use a distinctive replacement such as <strong>final</strong>.', repeated + prefix + warning, repeated + prefix + 'Extract the ZIP into a separate folder.'] },
    { type: 'title', text: seoTitle(locale, 'What the warnings mean', intro), level: 2 },
    { type: 'paragraph', html: repeated + prefix + warning },
    { type: 'tip', title: seoTitle(locale, 'Preview limit', intro), html: repeated + prefix + 'The ZIP contains new copies. It does not rename the source folder, so keep the originals until you check the result.' },
  ];
}
export function createContent(data: { slug: string; title: string; description: string; locale: string }): ToolLocaleContent<BatchFileNameNormalizerUI> {
  const faq = makeFaq(data.locale, data.title);
  const howTo = makeHowTo(data.locale);
  const faqSchema: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
  const howToSchema: WithContext<HowTo> = { '@context': 'https://schema.org', '@type': 'HowTo', name: data.title, description: data.description, step: howTo.map((step) => ({ '@type': 'HowToStep', name: step.name, text: step.text })) };
  const appSchema: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: data.title, description: data.description, applicationCategory: 'UtilityApplication', operatingSystem: 'All', offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' }, inLanguage: data.locale };
  return { ...data, slug: localizedSlugs[data.locale] ?? data.slug, ui: makeUi(data.locale), seo: makeSeo(data.locale), faq, howTo, bibliography, schemas: [faqSchema, howToSchema, appSchema] };
}
